name: mines_game_flutter
description: Mines using Flutter Casual Games Toolkit.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  flutter_hooks: ^0.20.1
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  parameterized_test: ^1.1.1

flutter:
  uses-material-design: true
